name: Security CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Security analysis with Bandit
      run: |
        source venv/bin/activate
        pip install bandit
        bandit -r . > bandit_report.txt

    - name: DAST with OWASP ZAP
      run: |
        docker run -t owasp/zap2docker-stable zap-baseline.py -t http://127.0.0.1:8000 -r zap_report.html || true

    - name: Upload Bandit and ZAP reports as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          bandit_report.txt
          zap_report.html
