name: Security CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask app
      run: |
        source venv/bin/activate
        export FLASK_APP=app.py
        nohup flask run --host=0.0.0.0 --port=8000 &

    - name: DAST with OWASP ZAP
      run: |
        docker pull zaproxy/zap-stable
        docker run -t zaproxy/zap-stable zap-baseline.py -t http://127.0.0.1:8000 -r zap_report.html || true

    - name: Stop Flask app
      run: |
        pkill -f "flask run"

    - name: Upload Bandit and ZAP reports as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          bandit_report.txt
          zap_report.html
